version: '3.4'

services:
  tfmodel:
    image: tf-model:latest
    container_name: tf-model
    ports:
      - 8008:8007
    volumes:
      - /opt/modelregistry/mlruns:/mlruns
      - /opt/mlservices/tf_model/app:/app
    environment:
      - LOG_LEVEL=DEBUG
      - TRACKING_SERVER='http://mlflow:5000'
    command: [ "gunicorn", "-b", "0.0.0.0:8007", "api:api", "--timeout", "1000", "--log-level", "debug" ]

